import { AdminMetricCard, AdminPageHeader, NotConnected } from '@/components/admin/admin-ui';
import { getAdminAnalyticsMetrics } from '@/lib/admin/mobile-repository';
import { requireAdminPage } from '@/lib/admin/session';

export const dynamic = 'force-dynamic';

export default async function MobileAnalyticsPage() {
  await requireAdminPage('analytics.read');
  const metrics = await getAdminAnalyticsMetrics();
  return <main className="admin-main" id="ana-icerik"><AdminPageHeader eyebrow="Mobil uygulama" title="İstatistikler" description="Yalnızca mevcut üretim şemasından ucuz ve güvenilir biçimde türetilebilen sayımlar." /><section className="admin-ops-section"><div className="admin-ops-section-heading"><div><p className="admin-kicker">Kullanıcılar</p><h2>Büyüme ve onboarding</h2></div></div><div className="admin-metric-grid"><AdminMetricCard label="Toplam" value={metrics.users} /><AdminMetricCard label="Bugün" value={metrics.today} /><AdminMetricCard label="Son 7 gün" value={metrics.last7} /><AdminMetricCard label="Son 30 gün" value={metrics.last30} /><AdminMetricCard label="Onboarding tamam" value={metrics.onboarding} /><AdminMetricCard label="Onboarding eksik" value={metrics.onboardingIncomplete} /></div></section><section className="admin-ops-section"><div className="admin-ops-section-heading"><div><p className="admin-kicker">Topluluk</p><h2>Mevcut göstergeler</h2></div></div><div className="admin-metric-grid"><AdminMetricCard label="Devre grubu" value={metrics.groups} /><AdminMetricCard label="Kanonik üyelik" value={metrics.memberships} /><AdminMetricCard label="DM konuşması" value={metrics.conversations} /><AdminMetricCard unavailable label="Grup mesajı" value={null} detail="Koleksiyon-grup özeti yok." /><AdminMetricCard unavailable label="DM mesajı" value={null} detail="Güvenilir aggregate yok." /></div></section><section className="admin-ops-section"><div className="admin-ops-section-heading"><div><p className="admin-kicker">Moderasyon</p><h2>Güvenlik durumu</h2></div></div><div className="admin-metric-grid"><AdminMetricCard label="Açık rapor" value={metrics.openReports} /><AdminMetricCard label="Çözülen rapor" value={metrics.resolvedReports} /><AdminMetricCard label="Askıya alınmış" value={metrics.suspended} /><AdminMetricCard label="Yasaklı" value={metrics.banned} /></div></section><section className="admin-funnel"><p className="admin-kicker">Ölçülebilen funnel</p><div><span><strong>{metrics.users}</strong>Kayıt</span><i>→</i><span><strong>{metrics.onboarding}</strong>Onboarding</span><i>→</i><span><strong>—</strong>Askerlik profili</span><i>→</i><span><strong>{metrics.memberships}</strong>Devre atandı</span><i>→</i><span><strong>—</strong>Topluluk etkileşimi</span></div></section><NotConnected title="Davranış analitiği bağlı değil">Hazırlık kullanımı, mesaj aktivitesi ve etkileşim funnel’ı için güvenilir aggregate/event kaynağı bulunmuyor; tahmin üretilmedi.</NotConnected></main>;
}
